### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by kekkoudesu** [flathub/net.devolutions.RDM#58]
Hi! I see this Flatpak package [was created by and maintained by Devolutions](https://blog.devolutions.net/2022/05/new-remote-desktop-manager-for-linux-now-available-on-flathub/), the developers of Remote Desktop Manager. I didn't realise this until finding the blog post just now.

It would be reassuring for users to know this package is maintained by the developers of RDM, which is what the "Verified" status communicates. This page explains how to get applications Verified on Flathub: https://docs.flathub.org/docs/for-app-authors/verification

Thanks for creating this package!

**Comment by sduguay-devolutions** [comment]
Hello!

Thank you for reaching out and for bringing this up. We've reached out to our DevOps team, and they'll be looking into it eventually.

Best regards.

**Comment by ChevalDentifrice** [comment]
Remote Desktop Manager is now verified on Flathub.
